### ISSUE TITLE
Filenames in multi-part volume

### ISSUE THREAD

**Issue by mjgarton** [nwaples/rardecode#19]
I have a use case where I want to know the names of all of the files in a multipart volume, and ideally know that they are all there and valid.

I am wondering about the best way to expose this so that I don't have to re-implement it elsewhere, since all of the interesting logic is in here already.

In my case, I want to know the filenames after extracting the whole archive, so somehow keeping a list of files processed during decoding and then exposing that would work for me.  Do you think that would be acceptable as an approach?

Alternatively, a specific API for asking the filenames, even if that means reading (parts of) the files again would work for me too.   Do you think that would be better?

Or is there a better approach than these?

If there is an approach you think is acceptable for this, I'm happy to attempt to implement it.

(In case it's interesting, my use case is that I want to decode a (possibly multi-part) archive, and delete the compressed archive files afterwards)

**Comment by nwaples** [comment]
If you want to know the filenames after extracting you should just keep a list of the FileHeader's (from Next()) as you extract them. 

Or in the experimental branch, there is a List() function. You can use that to get a list of files, which you can then open and read individually.

**Comment by nwaples** [comment]
Sorry, I understand now. I could probably do something like Volumes() which lists currently used volumes.

Also in the experimental branch you could pass a simple HTTPFileSystem option that just opened files while keeping a log. That would require no changes to the library.

**Comment by nwaples** [comment]
I just committed something slightly different.
I keep the filename as passed to os.Open() instead of what the opened file thinks it is (symlinks maybe). 
Also I add the volume file to the list as soon as its successfully opened. Maybe its useful to determine what volumes an individual file is in (by checking before and after reading a file).

I would merge experimental but that would probably break things for other users (api is different) so I have held off. Maybe when the few packages that use it move to go modules will I do it.

**Comment by mjgarton** [comment]
Thanks @nwaples that works for me!

**Comment by davidnewhall** [comment]
Was `.Volumes()` removed from v2.0.0? I cannot seem to find a replacement.

**Comment by nwaples** [comment]
Yes, looks like it. Put it back in.
